<a href="https://colab.research.google.com/github/juniorPalomino25/Python/blob/main/DL04_2do_EjemploKerasRegresion.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Ejemplo de Regresion con Keras para el conjunto de datos de Boston

In [24]:
from numpy import loadtxt
import tensorflow as tf
from keras.models import Sequential
from keras.layers import Dense

####Cargando el conjunto de datos

In [25]:
datos = loadtxt('housing.csv')

In [26]:
print(datos)

[[6.3200e-03 1.8000e+01 2.3100e+00 ... 3.9690e+02 4.9800e+00 2.4000e+01]
 [2.7310e-02 0.0000e+00 7.0700e+00 ... 3.9690e+02 9.1400e+00 2.1600e+01]
 [2.7290e-02 0.0000e+00 7.0700e+00 ... 3.9283e+02 4.0300e+00 3.4700e+01]
 ...
 [6.0760e-02 0.0000e+00 1.1930e+01 ... 3.9690e+02 5.6400e+00 2.3900e+01]
 [1.0959e-01 0.0000e+00 1.1930e+01 ... 3.9345e+02 6.4800e+00 2.2000e+01]
 [4.7410e-02 0.0000e+00 1.1930e+01 ... 3.9690e+02 7.8800e+00 1.1900e+01]]


In [27]:
datos.shape

(506, 14)

####Dividir la entrada (X) y la salida (Y)

In [28]:
X = datos[:,0:13]
Y = datos[:,13]

In [29]:
print(X.shape)
print(Y.shape)

(506, 13)
(506,)


####Definir el modelo

In [30]:
modelo = Sequential()

In [31]:
# Agregamos capas al modelo
modelo.add(Dense(15,input_dim=13, activation='relu'))
modelo.add(Dense(8, activation='relu'))
modelo.add(Dense(1))

Compilar el modelo

In [32]:
modelo.compile(loss='mean_squared_error', optimizer = 'adam',
               metrics=[tf.keras.metrics.RootMeanSquaredError()])

Entrenar el modelo

In [33]:
modelo.fit(X,Y,epochs=500, batch_size=10,verbose=0)

####Evaluar modelo

In [34]:
_ , metrica = modelo.evaluate(X,Y)
print('Raiz del promedio de los errores al cuadrado (RMSE): %.2f' % (metrica))

16/16 [==============================] - 0s 1ms/step - loss: 14.7563 - root_mean_squared_error: 3.8414
Raiz del promedio de los errores al cuadrado (RMSE): 3.84


##Realizar predicciones con el modelo

In [42]:
predicciones = modelo.predict(X)

Los 10 primeros resultados verdaderos

In [43]:
Y[0:10]

array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9])

Los 10 primeros resultados predichos

In [44]:
predicciones[0:10]

array([[33.19095 ],
       [24.360264],
       [33.26024 ],
       [33.268528],
       [29.51454 ],
       [27.11195 ],
       [23.29512 ],
       [22.108372],
       [19.002079],
       [21.354286]], dtype=float32)

Comparación con los 10 primeros casos

In [45]:
for i in range(10):
  print('%s => %f (esperado %d))' % (X[i].tolist(),predicciones[i],Y[i]))

[0.00632, 18.0, 2.31, 0.0, 0.538, 6.575, 65.2, 4.09, 1.0, 296.0, 15.3, 396.9, 4.98] => 33.190948 (esperado 24))
[0.02731, 0.0, 7.07, 0.0, 0.469, 6.421, 78.9, 4.9671, 2.0, 242.0, 17.8, 396.9, 9.14] => 24.360264 (esperado 21))
[0.02729, 0.0, 7.07, 0.0, 0.469, 7.185, 61.1, 4.9671, 2.0, 242.0, 17.8, 392.83, 4.03] => 33.260239 (esperado 34))
[0.03237, 0.0, 2.18, 0.0, 0.458, 6.998, 45.8, 6.0622, 3.0, 222.0, 18.7, 394.63, 2.94] => 33.268528 (esperado 33))
[0.06905, 0.0, 2.18, 0.0, 0.458, 7.147, 54.2, 6.0622, 3.0, 222.0, 18.7, 396.9, 5.33] => 29.514540 (esperado 36))
[0.02985, 0.0, 2.18, 0.0, 0.458, 6.43, 58.7, 6.0622, 3.0, 222.0, 18.7, 394.12, 5.21] => 27.111950 (esperado 28))
[0.08829, 12.5, 7.87, 0.0, 0.524, 6.012, 66.6, 5.5605, 5.0, 311.0, 15.2, 395.6, 12.43] => 23.295120 (esperado 22))
[0.14455, 12.5, 7.87, 0.0, 0.524, 6.172, 96.1, 5.9505, 5.0, 311.0, 15.2, 396.9, 19.15] => 22.108372 (esperado 27))
[0.21124, 12.5, 7.87, 0.0, 0.524, 5.631, 100.0, 6.0821, 5.0, 311.0, 15.2, 386.63, 29.93] =>